# Configuration for synthetic log events in a three-tier infrastructure

# Define common event templates
event_templates:
  web_access:
    type: "web_server"
    level: "INFO"
    message: "GET {{ url }} HTTP/1.1 {{ status_code }} {{ bytes_sent }} {{ user_agent }}"
    fields:
      url: "/{{ path }}"
      status_code: "200"
      bytes_sent: "{{ bytes_sent }}"
      user_agent: "{{ user_agent }}"

  app_request:
    type: "app_server"
    level: "INFO"
    message: "Processed request {{ request_id }} in {{ response_time }}ms"
    fields:
      request_id: "{{ request_id }}"
      response_time: "{{ response_time }}"

  db_query:
    type: "database"
    level: "INFO"
    message: "Executed query {{ query }} in {{ query_time }}ms"
    fields:
      query: "{{ query }}"
      query_time: "{{ query_time }}"

# Base traffic patterns
base_traffic:
  web_server:
    event_rate: 1000  # Events per hour
    patterns:
      - <<: *web_access
        fields:
          path: "index.html"
          bytes_sent: "12345"
          user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
      - <<: *web_access
        fields:
          path: "about.html"
          bytes_sent: "8765"
          user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 16_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1"

  app_server:
    event_rate: 500  # Events per hour
    patterns:
      - <<: *app_request
        fields:
          response_time: "50"
      - <<: *app_request
        fields:
          response_time: "100"

  database:
    event_rate: 300  # Events per hour
    patterns:
      - <<: *db_query
        fields:
          query: "SELECT * FROM users WHERE id = {{ user_id }}"
          query_time: "20"
      - <<: *db_query
        fields:
          query: "INSERT INTO logs (user_id, action) VALUES ({{ user_id }}, '{{ action }}')"
          query_time: "10"

# Anomalies
anomalies:
  - description: "Database slowdown on Thursday afternoon"
    start_time: "2023-10-12T14:00:00"
    end_time: "2023-10-12T18:00:00"
    patterns:
      - type: "database"
        level: "WARN"
        message: "Slow query execution: {{ query }} took {{ query_time }}ms"
        fields:
          query: "SELECT * FROM large_table WHERE condition = '{{ condition }}'"
          query_time: "5000"

  - description: "Unauthorized login attempts"
    start_time: "2023-10-13T09:00:00"
    end_time: "2023-10-13T10:00:00"
    patterns:
      - type: "web_server"
        level: "ERROR"
        message: "Failed login attempt from {{ ip_address }} for user {{ username }}"
        fields:
          ip_address: "192.168.1.100"
          username: "admin"

  - description: "Application crash on Friday evening"
    start_time: "2023-10-14T18:00:00"
    end_time: "2023-10-14T18:10:00"
    patterns:
      - type: "app_server"
        level: "CRITICAL"
        message: "Application crashed with error: {{ error_message }}"
        fields:
          error_message: "NullPointerException: Attempted to call method on null object"

  - description: "Increased error rate on web tier during peak hours"
    start_time: "2023-10-15T10:00:00"
    end_time: "2023-10-15T12:00:00"
    patterns:
      - type: "web_server"
        level: "ERROR"
        message: "500 Internal Server Error for {{ url }}"
        fields:
          url: "/api/v1/data"

# Variables for dynamic content
variables:
  user_id: ["1", "2", "3", "4", "5"]
  action: ["login", "logout", "view", "edit"]
  condition: ["true", "false", "unknown"]
  bytes_sent: ["12345", "8765", "9876", "4321"]
  user_agent:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
    - "Mozilla/5.0 (iPhone; CPU iPhone OS 16_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1"
    - "Mozilla/5.0 (Linux; Android 10; SM-G975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36"
  request_id: "REQ-{{ random_string(8) }}"
  response_time: "{{ random_int(10, 200) }}"
  query_time: "{{ random_int(1, 1000) }}"
  error_message: ["NullPointerException: Attempted to call method on null object", "OutOfMemoryError: Java heap space", "SQLGrammarException: Syntax error in SQL statement"]
  ip_address: "192.168.1.100"
  username: "admin"