start_time: "2024-12-09T10:00:00Z"
end_time: "2024-12-09T11:00:00Z"

response_time:
  min: 100
  max: 5000

sources:
  mysql:
    description: "MySQL error logs"
    volume:
      - pattern: "24/7"
        count: 10000
        distribution: "gaussian"
        details: {}
    attributes:
      timestamp:
        type: "timestamp"
        format: "%Y-%m-%d %H:%M:%S.%L"
      thread_id:
        type: "choice"
        values: ["12345", "12346", "12347", "12348", "12349", "12350", "12351", "12352", "12353", "12354", "12355", "12356", "12357", "12358", "12359", "12360", "12361", "12362", "12363", "12364", "12365", "12366", "12367", "12368", "12369", "12370", "12371", "12372", "12373", "12374", "23456", "23457", "23458", "23459", "23460", "23461", "23462", "23463", "23464", "23465", "23466", "23467", "23468", "23469", "23470", "23471", "23472", "23473", "23474", "23475", "23476", "23477", "23478", "23479", "23480", "23481", "23482", "23483", "23484", "23485", "23486", "23487", "23488", "23489", "23490", "23491", "23492", "23493", "23494", "23495", "23496", "23497", "23498", "23499", "23500", "23501", "23502", "23503", "23504", "23505", "23506", "23507", "23508", "23509", "23510", "23511", "23512", "23513", "23514", "23515"]
      error_level:
        type: "choice"
        values: ["Error", "Warning"]
      subsystem:
        type: "choice"
        values: ["InnoDB", "Server", "Query", "Performance", "Security", "Storage", "Replication"]
      error_code:
        type: "choice"
        values: ["1213", "1015", "1040", "1064", "1287", "1022", "1129", "1799", "1021", "1201", "1216", "1292", "1045", "1785", "1153", "1259", "1205", "1236", "1030", "1315", "1412", "1827", "1418", "1805", "1242", "1593", "1044", "1265", "1033", "1067", "1466", "1076", "1313", "1025", "1235", "1142", "1118", "1247", "1062", "1276", "1114", "1285", "1105", "1677", "1050", "1739", "1263", "1088", "1355", "1196", "1008", "1698", "1707", "1093", "1642", "1041", "1200", "1026"]
      message:
        type: "choice"
        values: [
          "Deadlock found when trying to get lock; try restarting transaction",
          "InnoDB: Cannot create temporary table",
          "Too many connections",
          "You have an error in your SQL syntax",
          "Using temporary table for subquery result",
          "Can't write; duplicate key in table 'users'",
          "Host '192.168.1.100' is blocked because of many connection errors",
          "Creating index without full text support",
          "Disk full",
          "Could not initialize master info structure",
          "Foreign key constraint fails",
          "Truncated incorrect DOUBLE value",
          "Access denied for user 'app_user'@'localhost'",
          "Read page with wrong checksum",
          "Got a packet bigger than 'max_allowed_packet'",
          "Multiple tables used in query without index",
          "Lock wait timeout exceeded",
          "Slave SQL thread stopped due to error",
          "Got error 28 from storage engine",
          "Query execution was interrupted",
          "Table corruption",
          "SSL connection error",
          "This table type requires a primary key",
          "Column count of mysql.proc is wrong",
          "Subquery returns more than 1 row",
          "Invalid default value for datetime column 'created_at'",
          "Cannot find tablespace for table 'archive_data'",
          "Shutdown in progress - no new connections allowed",
          "Error renaming table 'temp_users' to 'users'",
          "Thread pool queue full, dropping connection",
           "Transaction (1) with query UPDATE users SET last_login = '2025-01-03 08:23:15' WHERE id = 12345 and Transaction (2) with query UPDATE user_sessions SET status = 'active' WHERE user_id = 12345",
          "Temporary table space is full. allocated 2048MB of 2048MB",
          "Current connections: 501, Max connections: 500",
          "Syntax error near 'WEHRE age > 18' at line 1 in query: SELECT * FROM employees WEHRE age > 18",
          "Query: SELECT * FROM orders WHERE customer_id IN (SELECT id FROM customers WHERE country = 'US')",
          "Duplicate entry 'john.doe@example.com' for key 'email_unique'",
          "100 connection errors in last 60 seconds",
          "FULLTEXT index creation requires InnoDB_ft_enable_stopword=1",
          "Can't create new file '/var/lib/mysql/ibdata1'; errno: 28",
          "Master info repository is not configured",
          "Cannot delete from parent table 'departments' because foreign key constraint on 'employees' fails",
          "Value '12.34.56' could not be converted to DOUBLE",
          "Using password: YES, Invalid authentication factors",
          "Page [page_id=123456] in tablespace [orders] has wrong checksum",
          "Packet size: 16777216 bytes, Max allowed: 4194304 bytes",
          "Tables: orders, customers, products. Consider adding indexes",
          "Transaction waited 50 seconds for row lock on table 'orders'",
          "Could not execute Update_rows event on table 'customers'",
          "No space left on device; required: 1024MB, available: 100MB",
          "Query running for 600 seconds exceeded long_query_time",
          "Index corruption found in table 'products.idx_category'",
          "SSL connection error: SSL_CTX_set_tmp_dh failed",
          "Table 'audit_logs' has no primary key",
          "Expected 21 columns but found 20 in mysql.proc",
          "Subquery in UPDATE statement returned multiple rows",
          "Row size exceeded maximum length for table 'product_details'",
          "Semi-sync master wait for slave ACK timeout",
          "Cannot establish SSL connection: protocol version mismatch",
          "Foreign key check failed during online DDL operation",
          "Out of memory in table 'tmp_table'; try increasing tmp_table_size"
        ]
      
    event_types:
      - type: "mysql"
        format: "{timestamp},{thread_id},{error_level},{subsystem},{error_code}"
        create_from_scratch: true
