upload_config:
  axiom:
    max_concurrent_uploads: 512
    connection_pool_size: 4000
    batch_size: 1000000
    retry_attempts: 3
    retry_delay: 1.0
    upload_queue_size: 100000
    network_interfaces: 15

start_time: "2024-12-09T10:00:00Z"
end_time: "2024-12-09T11:00:00Z"

response_time:
  min: 100
  max: 5000

acceptable_values:
  method: ['GET', 'POST', 'PUT', 'DELETE']
  path: [
    '/api/v1/users', 
    '/api/v1/orders', 
    '/api/v1/products', 
    '/health', 
    '/metrics',
    '/api/v1/auth/login',
    '/api/v1/auth/logout',
    '/api/v1/cart',
    '/api/v1/wishlist',
    '/api/v1/reviews',
    '/api/v1/categories',
    '/api/v1/search',
    '/api/v1/profile',
    '/api/v1/notifications',
    '/api/v1/payments',
    '/api/v1/shipping',
    '/api/v1/inventory',
    '/api/v2/recommendations',
    '/api/v1/analytics',
    '/status'
  ]
  protocol: ['HTTP/1.1', 'HTTP/2.0']
  status:
    type: "choice"
    values: [
      # Success responses (~80%)
      200, 
      201, # Created (for POSTs)
      204,   # No Content (for DELETEs/updates)
      206,   # Partial Content (range requests)

      # Redirects (~5%)
      301, 301,  # Permanent redirects
      302, 302,  # Temporary redirects
      304,  # Not Modified (caching)

      # Client Errors (~12%)
      400, 400, 400,  # Bad Request
      401, 401, 401,  # Unauthorized
      403, 403,  # Forbidden
      404, 404, 404, 404,  # Not Found (common)
      408,  # Request Timeout
      429,  # Too Many Requests (rate limiting)

      # Server Errors (~3%)
      500, 500,  # Internal Server Error
      502,  # Bad Gateway
      503,  # Service Unavailable
      504   # Gateway Timeout
    ]
  user_agent: [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15',
    'Mozilla/5.0 (iPad; CPU OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1',
    'Mozilla/5.0 (Android 12; Mobile; rv:68.0) Gecko/68.0 Firefox/96.0',
    'Mozilla/5.0 (Linux; Android 11; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36',
    'Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-T510) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/13.0 Chrome/83.0.4103.106 Safari/537.36',
    'Mozilla/5.0 (Linux; Android 12; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.104 Mobile Safari/537.36',
    'Mozilla/5.0 (iPad; CPU OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148',
    'Mozilla/5.0 (Linux; Android 11; SM-T870 Build/RP1A.200720.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.104 Safari/537.36'
  ]
  referer: ['-', 'https://example.com', 'https://google.com']

sources:
  web_server:
    description: "Apache HTTP Server 2.4.62"
    dataset: "supervent"
    attributes:
      method:
        type: "choice"
        values: ['GET', 'POST', 'PUT', 'DELETE']
      path:
        type: "choice"
        values: ['/api/v1/users', '/api/v1/orders', '/api/v1/products']
      status:
        type: "choice"
        values: [200, 201, 400, 401, 403, 404, 500]
      bytes:
        type: "integer"
        min: 500
        max: 5000
    volume:
      - pattern: "24/7"
        count: 10000000
        distribution: "random"
    event_types:
      - type: "access"
        format: "{method} {path} {status} {bytes}"
        create_from_scratch: true

dependencies: []

event_frequencies:
  normal_traffic:
    web_server:
      access:
        frequency: "20000 per minute"
